apiVersion: v1
kind: Service
metadata:
  name: coordinator
  labels:
    app: coordinator
spec:
  type: LoadBalancer
  selector:
    app: coordinator
  ports:
    - name: http
      port: 80
      targetPort: 8090
